### ISSUE TITLE
Custom auto discovery rules 

### ISSUE THREAD

**Issue by pussinboots** [DataDog/datadog-agent#1250]
**Describe what happened:**

We try to setup a custom auto discovery rule that doesn't use one of the predefined template variables like %%host%% or %%port%%. 

Instead we defined our own variable like %%NODE_IP%% that also get replaced
by us with the proper environment variable. 

That is how the custom auto discovery template looks for datadog agent

```
ad_identifiers:
- kube-addon-manager-amd64

init_config:

instances:
- url: "http://%%NODE_IP%%:2379"
name: "%%container-name%%"
```

**Describe what you expected:**
I would expect when the ad_identifier is defined that it is 
always treated as an auto discovery template.

**Steps to reproduce the issue:**
Just create a auto discovery template configuration that doesn't use
the template variables.

**Additional environment details (Operating System, Cloud provider, etc):**

The background for that is that we have a running etcd process instance on one of our kubernetes nodes, its not run in a docker container just as a process on the node. On the same node runs a datadog-agent that should collect the metrics for that etcd process. Therefore the %%host%% template variable doesn't point to the node ip address. The nope ip address is resolved at runtime inside the datadog container by passing the following in the daemonset.yaml file.

```
- name: NODE_IP
   valueFrom:
     fieldRef:
       fieldPath: status.hostIP
```

Our auto discovery configuration is put in to the following folder 
/opt/datadog-agent/bin/agent/dist/conf.d/

We use the lates 6.0.0-beta.9 version.

We think the following code is related to this behaviour. 
https://github.com/DataDog/datadog-agent/blob/2bdc69dc336cb08d6a3b5274b93b2b13b25cd069/pkg/collector/autodiscovery/configresolver.go#L183

**Workaround**

The workaround we use now is to just define a template variable even if they is not used.
```
name: "%%container-name%%"
```

**Comment by pussinboots** [comment]
Hi @mfpierre 

thanks for the fast response. 

> I guess you have some sort of custom script to replace the %%NODE_IP%% variable inside the file template with the value of the environment variable?

We edit the entrypoint.sh script of the datadog 6.0.0 agent script to replace the NODE_IP variable. The value is provided by kubernetes. 

> If this is the case, you should be able to directly generate a static yaml configuration instead of trying to go though a template (especially if the process you want to monitor is not running in a container).

Yes that is the case we try to solve. 

For a better understanding we running the datadog agent inside a container that is deployed to a kubernetes cluster. The deployment is done as a daemon set through the helm [datadog chart](https://github.com/kubernetes/charts/tree/master/stable/datadog). The datadog agent container runs on all our kubernetes nodes, including the so called kubernetes master. On the kubernetes master all the control panel components are running like api server and also the etcd process. 

The etcd process is just running as a process on the OS level not inside the kubernetes cluster. On the k8s master runs an datadog agent as a container that should enable the etcd check just when it discover that it is running on the kubernetes master. That is actually done with the check if on the k8s node runs a kube-addon-manager-amd64 docker container then it means this datadog agent runs on the k8s master therefore activate the etcd check with the node ip instead the container ip address. 

The number of k8s master could also be greater then 1. 

I know that is an edge case for the auto discovery feature. May there is a more sophisticated way to achieve the same behaviour? 

My understanding of static configuration is that this static configuration describe then the k8s master and the datadog agent has to be deployed directly on the host not with k8s. 

Any feedback appreciated.

**Comment by xvello** [comment]
Hi @pussinboots ,

What you want to achieve (triggering checks depending on which processes run on a given host) is not in the current scope of the autodiscovery feature, that currently only listens to running containers.

To achieve this, we recommend you use static configuration files instead, which are definitely supported even when running the agent inside a container. You just need to expose a `/conf.d/etcd.yaml` file to the containers. The trick is to enable it only on master nodes: there are several ways to do so, depending on your cluster setup:

- mount a hostPath into `/conf.d`, and populate it differently on master nodes (add the `etcd.yaml` file on the masters, not on the workers)
- run two daemonsets: one on the masters with this conf mounted from a configmap, another on the rest of the cluster without it
- add it to all pods, and in your custom entrypoint, remove it if etcd does not run (either by scaping `/host/proc/`, `curl`ing the port, looking at the host IP...)

Because being able to inject envvars into autoconf templates can be a legit use case (for example if you need to monitors pods in host network mode, `%%host%%` will fail), I added a backlog item to implement `%%env_XXXXXX%%` template tags in the future.


Regards

**Comment by pussinboots** [comment]
Thanks for the response and the provided feedback.
