### ISSUE TITLE
Unable to find metrics_endpoint in config file or detect the kubelet URL automatically.

### ISSUE THREAD

**Issue by lemaral** [DataDog/datadog-agent#1387]
Using agent 6.0.0 deployed using latest chart on Kops/Kubernetes 1.7.8 (AWS), the following error is logged every 10 seconds:
[ AGENT ] 2018-03-04 19:53:30 UTC | ERROR | (runner.go:276 in work) | Error running check kubelet: [{"message": "Unable to find metrics_endpoint in config file or detect the kubelet URL automatically.", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/bin/agent/dist/checks/__init__.py\", line 332, in run\n    self.check(copy.deepcopy(self.instances[0]))\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/kubelet/kubelet.py\", line 103, in check\n    raise CheckException(\"Unable to find metrics_endpoint in config \"\nCheckException: Unable to find metrics_endpoint in config file or detect the kubelet URL automatically.\n"}]
[ AGENT ] 2018-03-04 19:53:32 UTC | ERROR | (autoconfig.go:446 in collect) | Unable to collect configurations from provider Kubernetes pod annotation: permanent failure in kubeutil: retry number exceeded
The Infrastructure/Containers page displays the Kubernetes informations, however there is no kubernetes_state metric available in the explorer.

**Comment by antoinepouille** [comment]
Hi,

Thanks for reaching out!
The kubernetes_state metrics are separate from the kubelet check, so this would be unrelated. This is most probably a configuration issue. So that we can investigate this, could you please [open a new support case](https://www.datadoghq.com/support/) where we will be able to assist you.
It will allow us to safely exchange your logs and configs through a flare.

Thanks

**Comment by ericfrancis** [comment]
```sh
# root@metrics-datadog-4c68v:/# env | grep DD_

DD_KUBERNETES_KUBELET_HOST=172.18.32.10
DD_DOGSTATSD_NON_LOCAL_TRAFFIC=false
DD_APM_NON_LOCAL_TRAFFIC=true
DD_TAGS=<>
DD_APM_ENABLED=true
DD_KUBERNETES_POD_LABELS_AS_TAGS={"app":"kube_app","release":"helm_release"}
DD_API_KEY=<>
DD_KUBERNETES_COLLECT_METADATA_TAGS=true
DD_LOGS_ENABLED=false
DD_JMX_USE_CGROUP_MEMORY_LIMIT=true
DD_COLLECT_KUBERNETES_EVENTS=true
DD_LOG_LEVEL=WARNING
DD_LEADER_LEASE_DURATION=60
DD_LEADER_ELECTION=true
DOCKER_DD_AGENT=yes
```

```
# root@metrics-datadog-4c68v:/# agent diagnose

=== Running Kubelet availability diagnosis ===
[DEBUG] GetKubeUtil: Init error: temporary failure in kubeutil, will retry later: unexpected status code 401 on endpoint https://172.18.32.10:10250/pods - 1525381569082275278
[ERROR] diagnose: temporary failure in kubeutil, will retry later: unexpected status code 401 on endpoint https://172.18.32.10:10250/pods - 1525381569082352380
===> FAIL
```

**Comment by carlosperezepfl** [comment]
@ericfrancis you solved the issue ?

**Comment by CharlyF** [comment]
Hello All, sorry for the late reply.
The logs show that the agent is getting a 401 when trying to connect to the kubelet.

```
Init error: temporary failure in kubeutil, will retry later: unexpected status code 401 on endpoint https://172.18.32.10:10250/pods
```

You would need to specify `kubelet_tls_verify:true` and configure `kubelet_client_crt` / `kubelet_client_key` otherwise the agent would not try to reach the kubelet over http and just fail.

This has since been fixed for version 6.21 to fallback to HTTP if this happens https://github.com/DataDog/datadog-agent/pull/1679.

The best option remains indeed to mount the certificates, or fix the auth delegation.

If you want to rely on the service account instead (and the rbac we provide), you need to make sure that the auth is properly delegated to the API Server.
To do so, you can add --authentication-token-webhook and --authorization-mode=Webhook to the ExecStart options of the kubelet systemd unit.

Could you upgrade the agent's version and let us know if that helps ?

**Comment by ericfrancis** [comment]
@carlosperezepfl I solved the issue by upgrading to agent v6.2.1.

@CharlyF upgrading fixed the issue. This issue can be marked closed.

That said. I am still a little confused.

There are 3 fixes that are better than using the http fallback:
1. mount the certs
1. fix auth delegation
1. Use rbac and pass --authentication-token-webhook

I'm not clear on what "fix the auth delegation" means. Could you point me to docs?

As for rbac, I do not have access to change "ExecStart options of the kubelet systemd".

So, I'm guessing that the correct/best fix for my situation would be to mount the correct certificates.

**Comment by antoinepouille** [comment]
@ericfrancis 2 and 3 are actually the same point. The auth delegation from the kubelet to the apiserver is done through webhooks.

Mounting the correct certificates should be the way to go here. However you will still need a correct RBAC to get permissions

**Comment by recipedude** [comment]
Had a similar issue that was spewing forth "Unable to detect the kubelet URL automatically." in the agent's pod logs. 

Adding the following environment variable to our deployment resolved the issue for us. YMMV

```DD_KUBELET_TLS_VERIFY: false```

**Comment by mopalinski** [comment]
Since this is the issue that pops up when I search for the following error:
`Unable to find metrics_endpoint in config file or detect the kubelet URL automatically`
I figured I'd post the solution I found most straight forward.

This issue still occurs on current version of agent (7.21.1) when following documentation while deploying on EKS (K8s 1.16).
In my case this issue simply occurs because of deprecation of kubelet's read only (unencrypted) endpoint (port 10255) which is what the agent defaults to when proper config for HTTPS endpoint is not provided.

The solution is quite simple. You need to mount the service account token and certificate and tell the agent where they are by doing the following:
1. setting `automountServiceAccountToken` parameter to `true` in your daemonset spec
2. setting the following env vars for the `agent` container:
- `DD_KUBELET_CLIENT_CA` to `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
- `DD_BEARER_TOKEN_PATH` to `/var/run/secrets/kubernetes.io/serviceaccount/token`

Seems to me that this should be a default at this point considering the non-SSL endpoint is deprecated in more recent version of K8s and SSL is really more preferable in general.
