### ISSUE TITLE
Kubernetes: Agent should not run kubernetes_apiserver if not leader

### ISSUE THREAD

**Issue by sylr** [DataDog/datadog-agent#1408]
![datadog-kube-apiserver](https://user-images.githubusercontent.com/153052/37048722-078e7930-216f-11e8-9bb3-d8a6f0c4415b.PNG)

`kubernetes_apiserver` app reports errors  on all nodes that are not elected leader, it shouldn't be  ran at all on those nodes as long as they are not leader.

```
Datadog's kubernetes_apiserver integration is reporting:
Instance #kubernetes_apiserver[ERROR]:not Leader
```

Curiously `kubernetes_apiserver` is not reported on the interface on the elected leader (4th line) although it's working : 

```
root@datadog-datadog-l3hm9:/# agent status | grep -A5  kubernetes_apiserver
    kubernetes_apiserver
    --------------------
      Total Runs: 769
      Metrics: 0, Total Metrics: 0
      Events: 3, Total Events: 281
      Service Checks: 3, Total Service Checks: 186
```

**Comment by CharlyF** [comment]
Hey @sylr thanks for letting us know.
This should be fixed in 6.0.1 thanks to this https://github.com/DataDog/datadog-agent/pull/1395/files.
As for the thumbnail not showing up, I'm looking into it.

**Comment by CharlyF** [comment]
The current status: The agents not leading will not return an error thanks to the above fix, hence the integration thumbnail will not show up as yellow. The reason why the actual leader does not have a thumbnail is because the check is successfully run but does not submit metrics.
I'm going to improve the check for it to collect metrics from the control plane, it should be available in the coming weeks. This will make the thumbnail show up for the leader and only the leader will run the check from the UI standpoint.

**Comment by sylr** [comment]
Thanks @CharlyF !
