### ISSUE TITLE
[BUG] High Security Vulnerability 

### ISSUE THREAD

**Issue by brandocomando** [DataDog/datadog-agent#15365]
**Agent Environment**
Latest datadog agent docker container

**Describe what happened:**
Scanned docker image with Snyk and found high vulnerabilities
https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMEMICKLEIGORESTFULV3-2435654

**Describe what you expected:**
Snyk scan would not report any issues

**Steps to reproduce the issue:**
Scan Datadog agent container

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by clamoriniere** [comment]
This vulnerability should already be fixed (https://github.com/DataDog/datadog-agent/pull/12730) in this repo and the release `7.39.0`

The scanner might still see the error because the fix was backported on `github.com/emicklei/go-restful` `v2` branch by https://github.com/emicklei/go-restful/pull/503 and released in `2.16.0` 

We can see that we are using this version here: https://github.com/DataDog/datadog-agent/blob/main/go.mod#L339
