### ISSUE TITLE
Cannot decode v0.5 traces payload: encoded span needs exactly 12 elements in array

### ISSUE THREAD

**Issue by gliderkite** [DataDog/datadog-agent#15620]
I'm running [the opentelemetry example](https://github.com/open-telemetry/opentelemetry-rust/tree/main/examples/datadog) with [DataDog agent running on a Docker container](https://docs.datadoghq.com/containers/docker/?tab=standard) (v7.42.1) with default configuration in a MacOS (aarch64-darwin).

Running as is gives me on the Rust application the following error:

```
OpenTelemetry trace error occurred. request failed with status 400 Bad Request
```

While I can see on the agent logs the following one:

```
2023-02-15 11:12:44 UTC | TRACE | ERROR | (run.go:275 in Errorf) | Cannot decode v0.5 traces payload: encoded span needs exactly 12 elements in array
```

If I change the API version to `v0.3` I can successfuly see the traces in the DataDog dashboard.

```rust
let tracer = new_pipeline()
        .with_service_name("trace-demo")
        .with_api_version(ApiVersion::Version03)
        .install_simple()?;
```

Are there any changes I need to make in my configuration or setup to be able to use `v0.5` (as far as I know it requires datadog-agent v7.22.0+)?

**Comment by vickenty** [comment]
Hi @gliderkite,

This appears a bug in the opentelemetry library, as it encodes 13 instead of 12 as the array length: https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-datadog/src/exporter/model/v05.rs#L157

It seems you have already reported it in the `opentelemetry-rust` repository, so I'm going to close this issue here. Please feel free to reach out to [Datadog support](http://docs.datadoghq.com/help/) if you have any further questions.

Thanks!
