### ISSUE TITLE
[BUG] High Security Vulnerability found (com.github.jnr:jnr-posix)

### ISSUE THREAD

**Issue by nick-chan-mox** [DataDog/datadog-agent#16382]
**Agent Environment**
Latest Datadog Agent container image version `7.43.1`

**Describe what happened:**
Scanned docker image with Snyk and found a high vulnerability:
https://security.snyk.io/vuln/SNYK-JAVA-COMGITHUBJNR-1570422

**Describe what you expected:**
Snyk scan would not report any issues

**Steps to reproduce the issue:**
Scan Datadog agent container

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by remeh** [comment]
Thank you for having opened this issue. This issue tracker is primarily used to track bugs in the Agent codebase to completion. For issues directly related to your use of the agent, we have a dedicated team who can investigate your reports directly. Please contact [Datadog support](http://docs.datadoghq.com/help/) and send them a [flare](https://docs.datadoghq.com/agent/troubleshooting/#send-a-flare) demonstrating the issue.

Thanks!

**Comment by Kyslik** [comment]
This is still not fixed in DD 7.45.x :(.

**Comment by Kyslik** [comment]
This is still not fixed in DD 7.52.x :(.

**Comment by paulcacheux** [comment]
Hello @rdsedmundo  thanks for reaching out. This issue has been reported multiple times before and we cannot update the library because of our support of java 1.7. You will find more explanation about this and why we think this CVE does not impact us in https://github.com/DataDog/java-dogstatsd-client/pull/155#issuecomment-918278319
