### ISSUE TITLE
Upgrade embedded Python

### ISSUE THREAD

**Issue by dan-blanchard** [DataDog/datadog-agent#1907]
The embedded Python is still 2.7, and that is [rapidly approaching EOL on January 1, 2020](https://pythonclock.org/). We just ran into an issue today where one of our checks was written assuming Python 3.6 (since that's what the rest of our codebase uses), and then it crashed and burned because the embedded Python is so old. 

It would be great if there was a way to point to a different Python interpreter or things were just upgraded.

**Comment by olivielpeau** [comment]
Hi @dan-blanchard, thanks for the concern. We have plans to upgrade the embedded Python v2.7 to v3 before 2.7's EOL, but no timeline that we can share at this point. We'll update the issue when we have more info to share, thanks!

**Comment by dan-blanchard** [comment]
Just hit this again. It's really frustrating that we're forced to litter our codebase with compatibility hacks to work with legacy Python.

**Comment by dan-blanchard** [comment]
[Python 2.7 EOL is less than 9 months away](https://pythonclock.org/). Can you offer any updates on the timeline here?

**Comment by dan-blanchard** [comment]
4 months and 22 days left until Python 2.7 EOL. Any updates?

**Comment by dsahni** [comment]
Hi @dan-blanchard 👋 
We had followed up earlier via email about this back in August, but also reaching out here. Datadog Agent v6.14.0 introduces the ability to run the Python 3 runtime instead of Python 2. You can find more information about how to enable this mode, as well as tips on migrating any custom checks to Python 3 on our [docs page here](https://docs.datadoghq.com/agent/guide/python-3).
If you run into any issues, please reach out to support@datadoghq.com and we'll be happy to help out. Thank you!

**Comment by dsahni** [comment]
Closing out this issue, now that Datadog Agent 6.14+ includes the option of enabling the Python 3 runtime.
