### ISSUE TITLE
[BUG] Kubernetes - Hostnames are sometimes incorrect

### ISSUE THREAD

**Issue by myoung34** [DataDog/datadog-agent#23148]
**Agent Environment**
7.50.2

**Describe what happened:**

Some nodes have the incorrect hostname in the UI, but are configured and report as expected in logs, config, and `agent hostname`

```
✗ k -n datadog exec -it pod/datadog-27c9h -c agent /bin/sh
# agent hostname
cluster21
```

It shows cluster21 for pod `datadog-27c9h` but the UI has this lasted **always** as `datadog-hhqvz`

The container logs also seem correct:

```
INFO | (cmd/agent/subcommands/run/command.go:363 in startAgent) | Starting Datadog Agent v7.50.2
INFO | (cmd/agent/subcommands/run/command.go:425 in startAgent) | Hostname is: cluster21
```

However it never matches. Oddly enough _some_ do, but only 3 out of 8 despitet having the same configuration across all

![image](https://github.com/DataDog/datadog-agent/assets/879922/24a1fc1b-0345-440c-b3a1-c9cbcb18a02e)

**Describe what you expected:**

Agent hostname in the UI should match what is being reported downwards

**Steps to reproduce the issue:**
Unsure, however my chart in its entirety is here for inspection (this is live version for argocd, not a copy): https://github.com/myoung34/homelab/tree/main/k8s/prod/datadog

**Additional environment details (Operating System, Cloud provider, etc):**
on prem (talos)

**Comment by sgnn7** [comment]
Hi @myoung34,
Based on your information, I think this is more likely to be a problem with configuration of the Agent than a bug (`DD_HOSTNAME: spec.nodeName` setting), possibly an issue with host expiration, and/or even temporal aliasing issues (hostnames/aliases changing over time but linked historically by overlap in hostname/alias). Since extra verbose information would be needed (in form of a support [flare](https://docs.datadoghq.com/agent/troubleshooting/send_a_flare/?tab=agentv6v7)/ticket) and other potentially-sensitive info from your test deployment, I would recommend that you go that route for investigating the discrepancy.

For now I'll close this issue but we can discuss things here and/or reopen the issue if turns out that there's something on the Agent-side that needs fixing.

Thanks,
Srdjan
