### ISSUE TITLE
Cluster-Agent / HPA : no kind is registered for the type v1.Status

### ISSUE THREAD

**Issue by trondhindenes** [DataDog/datadog-agent#2955]
I'm trying to get the Custom Metrics server up and running, but it's not exposing any metrics. Here's what I see:

Output from `datadog-cluster-agent status` (only pasted the relevant part)
```
  Custom Metrics Server
  =====================
    ConfigMap name: sre/datadog-custom-metrics
    
    External Metrics
    ----------------
      Total: 0
      Valid: 0
```

When curling the custom metrics service registered as an ApiService I get:
`: no kind is registered for the type v1.Status`

When looking at the same service as exposed thru kube-apiserver:
```
curl http://localhost:8001/apis/external.metrics.k8s.io/v1beta1
{
"kind": "APIResourceList",
"apiVersion": "v1",
"groupVersion": "external.metrics.k8s.io/v1beta1",
"resources": []
}
```

Status from `kubectl get apiservice v1beta1.external.metrics.k8s.io` also reports all checks passed.

As far as I can see, everything lines up nicely, just that no metrics are present. What should I do to further troubleshoot this?

**Comment by trondhindenes** [comment]
Realizing that this might be because the "regular" agents don't correctly discover the cluster agent. It would be good if the documentation was explicit about how this is performed. Is it based on a hard-coded service name or similar?

**Comment by trondhindenes** [comment]
Ah. Turns out that can be configured using `DATADOG_CLUSTER_AGENT_SERVICE_HOST` on the node agent. Good to know!

**Comment by trondhindenes** [comment]
so that didn't work, I'm getting:
```
=====================
Datadog Cluster Agent
=====================

  - Could not detect the Datadog Cluster Agent's endpoint: temporary failure in clusterAgentClient, will retry later: cannot get a cluster agent endpoint for kubernetes service DATADOG_CLUSTER_AGENT, env  is empty

  - Could not retrieve the version of the Datadog Cluster Agent.

```

**Comment by trondhindenes** [comment]
Anyways, still not getting any metrics from the custom metrics server so the problem remains.

**Comment by trondhindenes** [comment]
So I finally discovered that the metrics server will only contain data if there are HPA's configured, that threw me for a bit, and should maybe be explicitly documented.

**Comment by CharlyF** [comment]
Hey @trondhindenes,

Thank you very much for opening this issue, and apologies for the slight delay.
Indeed, the external metrics server (Datadog Cluster Agent) will only provide values to the APIServer on the `/apis/external.metrics.k8s.io/v1beta1/namespaces/<ns>/<metric_name>` route if there is an HorizontalPodAutoscaler configured for the `<ns>/<metric_name>` combo.

The workflow in this design is to use your Datadog account to visualise and chose the metrics you want to use to autoscale your deployments, instead of curl'ing the external metrics server.

Thank you for the feedback nonetheless, we'll make sure the documentation is clearer!

Feel free to reach back out should you have questions/issues.

Best,
.C
