### ISSUE TITLE
log_processing_rules ignored when DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL

### ISSUE THREAD

**Issue by zakkg3** [DataDog/datadog-agent#2958]
**Steps to reproduce the issue:**
run helm datadog agent chart with values:

        datadog:
          logsEnabled: true
          logsConfigContainerCollectAll: true # <-- change this to make ir work
          confd:
            nohealthchecks.yaml: |-
              logs:
                - type: docker
                  service: docker
                  source: docker
                  log_processing_rules:
                  - type: exclude_at_match
                    name: exclude_healthchecks
                    pattern: '\s200\s[1-7][0-9][0-9][0-9]\s"-"\s"kube-probe\/1\.10"\s"-"'

**Additional environment details (Operating System, Cloud provider, etc):**
K8s (EKS)
datadog/agent:6.6.0

By setting DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL to false fix the problem and logs are being filtered
similar to https://github.com/DataDog/datadog-agent/issues/1736

**Comment by NBParis** [comment]
Hello @zakkg3,

In general, I would advise to open a support ticket at support@datadoghq.com to get an answer in a timely manner and so we can help you identify if this is a setup issue or a bug at the agent levels.

Let me explain what happens there:

By default the collect all environment variable behaves in a similar way as mounting a configmap with the docker type collection for logs.
The biggest difference is that we now automatically set the source and service depending on the `short_image` tag instead of having a default `docker` for service and source.

Now if you have collect all AND a config map with the `docker` log collection type, both overlaps and only one of those is used (I unfortunately cannot guarantee which one but according to your example it seems that the environment variable takes the lead).

Which is why I would advise to use only of those but not both options.

Now, it seems that you are willing to exclude some logs and for this I would actually advise to use the configuration explained there: https://docs.datadoghq.com/logs/log_collection/docker/?tab=containerinstallation#filter-containers

Another solution to filter out some logs is to do it directly on the Datadog side thanks to Exclusion filter: https://docs.datadoghq.com/logs/logging_without_limits/#exclusion-filters

Let me know if that helps.

I'll go ahead and close this issue but feel free to ping support@datadoghq.com for more details if you still have questions on that topic.

Thanks a lot,
Nils
