### ISSUE TITLE
Logs are not correlated to traces

### ISSUE THREAD

**Issue by linyaoli** [DataDog/datadog-agent#3182]
Hi there, I'm seeing an issue that the logs are not correlated with traces, and the hint is

![Screenshot 2019-03-21 at 1 53 08 PM](https://user-images.githubusercontent.com/1335416/54735465-4f335600-4be1-11e9-84bf-3e4f006df910.png)

and in APM page, I can only find very few traces are attached with **only** one log. Most of them are not correlated at all.

Originally I tested in my dev environment and everything went well, but after deployed to actual servers, this issue came out.

My instinct is that the agent samples too much as what it is mentioned in your official document:

------

**Agent sampling:** Reduces the resources and network used by the Agent for sending traces to the backend. Configurable, default to a maximum of 10 traces per second.

------

**Additional environment details (Operating System, Cloud provider, etc):**
Our infrastructure is fully containerized in k8s and running in AWS.

Please advise, thanks in advance.

**Comment by gbbr** [comment]
Hi 👋 

Since this involves various areas of the product, my advice is to try and reach out to support because they have broader knowledge and they might help you investigate deeper. The problem might not be in the agent. If by any chance it is, we'll be able to communicate further by means of that channel.

We can update this issue later based on how we move forward.

**Comment by linyaoli** [comment]
@gbbr thank u! I'm currently in a discussion with the support engineers and will update once it's figured out. 

cheers.

**Comment by linyaoli** [comment]
Fixed, was caused by trace sampling and wrongly defined json formats.
