### ISSUE TITLE
6.11.2 tag missing from Docker Hub

### ISSUE THREAD

**Issue by rafaelmagu** [DataDog/datadog-agent#3536]
I noticed 6.11.2 has been released a couple of days ago but Docker Hub only has 6.11.2-rc.2.

Is there no automated pipeline for this?

**Comment by arbll** [comment]
Hi @rafaelmagu,

Thanks for the report. I have checked and `6.11.2` is actually not released yet.

I am wondering what made you think it was? Was it the [github release page](https://github.com/DataDog/datadog-agent/releases)?
This page is a bit confusing since it lists all git tags as "releases". Tagging is part of our build process but does not necessarily mean that an artifact has been made public yet.

If you go to the [second page](https://github.com/DataDog/datadog-agent/releases?after=dca-1.3.0-rc3) of the release list you will see that `6.11.1` is marked as "Latest release".

`6.11.2` should be available later today

Arthur

**Comment by arbll** [comment]
`6.11.2` artifacts are out, closing

Thanks again for being vigilant.
