### ISSUE TITLE
Datadog Agent tries to fetch hostname from GCE when provider is AWS.

### ISSUE THREAD

**Issue by jannylund** [DataDog/datadog-agent#3566]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

===============
Agent (v6.11.2)
===============

  Status date: 2019-05-26 12:35:53.919502 UTC
  Agent start: 2019-05-24 05:17:30.025123 UTC
  Pid: 337
  Python Version: 2.7.16
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -748µs
    System UTC time: 2019-05-26 12:35:53.919502 UTC

  Host Info
  =========
    bootTime: 2019-05-03 05:51:42.000000 UTC
    kernelVersion: 4.9.0-7-amd64
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: buster/sid
    procs: 64
    uptime: 503h25m56s

  Hostnames
  =========
    ec2-hostname: <REDACTED>.eu-west-1.compute.internal
    host_aliases: [<REDACTED>.k8s.local]
    hostname: i-<REDACTED>
    instance-id: i-<REDACTED>
    socket-fqdn: datadog-agent-6hzkg
    socket-hostname: datadog-agent-6hzkg
    hostname provider: aws
    unused hostname providers:
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

```
**Describe what happened:**
Datadog-Agent tries to fetch hostname from GCE metadata endpoint while running on AWS.
`gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname`

**Describe what you expected:**
Hostname would be fetched from ec2 metadata api as per: https://github.com/DataDog/datadog-agent/blob/e47ccf7147139efd36d6e05e3de63f776a32d2b1/pkg/util/ec2/ec2.go#L33

**Steps to reproduce the issue:**
-

**Additional environment details (Operating System, Cloud provider, etc):**
Datadog agent is deployed as a daemonset on kubernetes. Cluster is deployed using KOPS, running on AWS EC2 instances.

**Comment by jannylund** [comment]
Err. I read the code and it seems to be completely normal that it actually walks trough everything?
I assume this is working as expected then.

https://github.com/DataDog/datadog-agent/blob/98a6c25b581f381d80a90bb408d30dcf8620d015/pkg/util/hostname.go#L198

**Comment by Mazyod** [comment]
It does seem to be working as expected, but the rule of least astonishment might have been violated. Why should there be warning logs about GCE when the agent is deployed in a completely unrelated environment? I believe there is room for improvement here.

**Comment by sudhi-evang** [comment]
We just noticed similar issue in one of the EC2 kubernetes worker node

`2022-01-30 21:17:14 UTC | CORE | WARN | (pkg/util/gce/gce_tags.go:48 in getCachedTags) | unable to get tags from gce and cache is empty: status code 401 trying to GET http://169.254.169.254/computeMetadata/v1/?recursive=true
2022-01-30 21:17:14 UTC | CORE | WARN | (pkg/util/ec2/ec2_tags.go:90 in GetTags) | unable to get tags from aws and cache is empty: unable to fetch EC2 API, status code 401 trying to fetch http://169.254.169.254/latest/dynamic/instance-identity/document/`

We suspect reuse of IP from different host leads to this? Not sure though.

**Comment by rdgangi** [comment]
Are you using [EC2 metadata with IMDS v2]?
Try to set ec2_prefer_imdsv2: true in config file and restar the agent

**Comment by RajSmarsh** [comment]
setting ec2_prefer_imdsv2: true doesn't help

**Comment by michelzanini** [comment]
I managed to make this warning disappear today by configuring `cloud_provider_metadata` to `aws` only.
This property is on the agent configuration or, it's also available as an environment variable.

I am using the agent with Helm on EKS, so I added:

```
agents:
  containers:
    agent:
      env:
        - name: DD_CLOUD_PROVIDER_METADATA
          value: "aws"
```

That solves it. No more GCE warnings.
If anyone else finds this useful.

**Comment by DanRoestorf** [comment]
This happens on AWS ECS Fargate as well.

**Comment by knusbaum** [comment]
Reopening this. As @Mazyod mentioned, this should not be issuing warnings like this as it is confusing.

**Comment by sgnn7** [comment]
Hey everyone,
We will likely not be removing nor lowering the warning level around these messages so I will re-close the issue but I wanted to add the full context here around why this is a difficult UX problem and why we are taking this specific direction. With that said, we may add some language in those log messages that `cloud_provider_metadata` config option should be used to reduce the noise if specific cloud provider(s) should be skipped.

### Longer Context 📜 

One of the most important things that the Agent does at start-up is to self-identify its hostname, runtime environment, and collect any information about itself that it needs so that metrics/views in the app are properly correlated. For most cloud environments we know that polling the metadata endpoint(s) is the best way to do this but if the user has not given us hints (through `cloud_provider_metadata` config option) on what to expect, the Agent cannot know what it is running on (is it AWS? is it GCE? 🤷). Because of that, we _must_ iterate over all the cloud providers' endpoints to get the best possible source of data.

So with that in mind, you may ask why not then turn these warnings into `DEBUG`/`INFO` messages? When the Agent has no hints of what environment it is running on, there is no reliable way for us to tell if a metadata endpoint is not present (e.g. we're not running on that cloud provider) or if the metadata is just unreachable (e.g. we're on AWS but AWS metadata endpoint has been blocked by policy). If we turned these warnings into lover level logging messages, identifying problems (e.g. by `grep`ing over the logs or by reading the status output) becomes significantly harder for the deployment/ops team but it does come at the cost of extra messages for cloud providers that aren't needed.

Taking all of that into account, we are inclined to keep the current behavior but maybe we will add some information that if a specific errored cloud provider should not be attempted that `cloud_provider_metadata` can be used to squelch it.

Hope this answers some of the deeper questions around this functionality and the reasoning behind the current Agent's behavior.
