### ISSUE TITLE
Installation script not working

### ISSUE THREAD

**Issue by alexrs** [DataDog/datadog-agent#3597]
**Describe what happened:**
When trying to execute `bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_mac_os.sh)"`, I get the error `mknod: node type must be 'b' or 'c' or 'w'.`. 

The issue seems to be in https://github.com/DataDog/datadog-agent/blob/master/cmd/agent/install_script.sh#L26

**Describe what you expected:**
Datadog agent being installed

**Steps to reproduce the issue:**
Run `bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_mac_os.sh)"`

**Additional environment details (Operating System, Cloud provider, etc):**
macOS 10.14.4

**Comment by KSerrania** [comment]
@alexrs Thanks for reaching out! Are you sure you didn’t use this command instead:
`bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh)”`?
Seeing your error, I believe you may have used the linux install script, since `mknod` is only used in this one.

**Comment by alexrs** [comment]
You are right 🤦‍♂
