### ISSUE TITLE
Rationale for custom timestamp format instead of ISO/Please use ISO timestamp formats

### ISSUE THREAD

**Issue by lattwood** [DataDog/datadog-agent#5222]
Is there a reason for DataDog to use a custom timestamp format here instead of the ISO standard? https://github.com/DataDog/datadog-agent/blob/656c274769a3ae8a284d569caa262f79ed1a334d/pkg/config/log.go#L27

**Describe what happened:**
This custom timestamp format was picked up by Elasticsearch as a string, causing an index mapping conflict and much sadness. MUCH SADNESS.

**Describe what you expected:**
I expected DataDog to use the ISO standard, so my Elasticsearch cluster could correctly autodetect the correct field mapping type.

**Steps to reproduce the issue:**
Use logstash to json decode datadog agent log output and dump it into ES.

The default parser for ES for date fields is `strict_date_optional_time`, which their documentation defines as: A generic ISO datetime parser where the date, in year_month_day format, is mandatory and the time, separated by T, is optional. Examples: `yyyy-MM-dd'T'HH:mm:ss.SSSZ` or `yyyy-MM-dd`.

**Comment by remeh** [comment]
Hey @lattwood,

Thanks for having opened an issue about this.

We've discussed this and we consider emitting the Datadog Agent logs with another time format (and yes, RFC3339 is an option). I don't know for now if this will be the new default or if there will be an opt-in configuration field, but we'll work on that.

In the meantime, isn't there a way to indicate to ES that ingesting these logs for this index are using a custom date format? https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#custom-date-formats
I guess that you can't use that because you're ingesting logs from another source as well for this index?

We'll update this issue when we start working on this.

**Comment by lattwood** [comment]
Bingo. We’re just using the default indexing template with shard quantities
increased for _reasons_. As well, we have other applications using the time
field with time stamps parsable with the default mapping, so this only
occasionally broke Kibana before I just told logstash to drop the time
field. I think even the default golang time stamp format would result in
better operability.

**Comment by olivielpeau** [comment]
Late update: https://github.com/DataDog/datadog-agent/pull/5697 (shipped in v`7.21.0`/`6.21.0`) added the agent config option `log_format_rfc3339` that changes the timestamp format in agent logs to RFC3339 when enabled.

We'll make this behavior the default in a future major version. Closing this, thanks @lattwood for the feedback!

**Comment by lattwood** [comment]
@olivielpeau just noticed this now, thanks for following up with this! 👏🏻
