### ISSUE TITLE
Datadog version 7.20.0 causes regression of redisdb check

### ISSUE THREAD

**Issue by neb14** [DataDog/datadog-agent#5715]
https://github.com/DataDog/integrations-core/issues/6875

The ticket above is the particular issue.  The quick fix for datadog-agent would be to replace redisdb version 2.1.0 with version 2.0.2.

**Comment by mx-psi** [comment]
Hi, thanks for reporting this! We are looking into it.

**Comment by neb14** [comment]
upstream integrations-core has a fix

**Comment by neb14** [comment]
7.20.1 has the same regression, can we get a release with the latest integrations-core?

**Comment by mx-psi** [comment]
Hi @neb14, the redis integration was not updated on 7.20.1 but will be updated in the next bugfix release for 7.20. 

In the meantime since the integration has been fixed you can manually update the integration following the instructions that @ChristineTChen left [in a comment](https://github.com/DataDog/integrations-core/issues/6875#issuecomment-644188835) in the other issue.

**Comment by mx-psi** [comment]
This is fixed in [7.20.2](https://github.com/DataDog/datadog-agent/releases/tag/7.20.2). Feel free to reopen if needed.
