### ISSUE TITLE
Can't install agent on Ubuntu 16.04

### ISSUE THREAD

**Issue by xeroxoid** [DataDog/datadog-agent#5971]
**Describe what happened:**
Tried to install the datadog-agent on a new Ubuntu host and the installation failed with the following message: 
```
* Installing apt-transport-https

Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Hit:4 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial InRelease
Ign:5 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 InRelease
Get:6 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Hit:7 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 Release
Hit:8 https://apt.datadoghq.com stable InRelease
Fetched 325 kB in 0s (480 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version (1.2.32ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 82 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
dirmngr is already the newest version (2.1.11-6ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 82 not upgraded.

* Installing APT package sources for Datadog

Executing: /tmp/tmp.KrDIWsZ1xN/gpg.1.sh --recv-keys
--keyserver
hkp://keyserver.ubuntu.com:80
A2923DFF56EDA6E76E55E492D3A80E30382E94DE
gpg: requesting key 382E94DE from hkp server keyserver.ubuntu.com
gpg: key 382E94DE: "Datadog, Inc <package@datadoghq.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

* Installing the Datadog Agent package

Hit:1 https://apt.datadoghq.com stable InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package datadog-agent
ERROR
Failed to install the Datadog package, sometimes it may be
due to another APT source failing. See the logs above to
determine the cause.
If the cause is unclear, please contact Datadog support.
*****

It looks like you hit an issue when trying to install the Agent.

Troubleshooting and basic usage information for the Agent are available at:

    https://docs.datadoghq.com/agent/basic_agent_usage/

If you're still having problems, please send an email to support@datadoghq.com
with the contents of ddagent-install.log and we'll do our very best to help you
solve your problem.
```

**Steps to reproduce the issue:**

Run `DD_AGENT_MAJOR_VERSION=7 DD_API_KEY=xxxx_removed_xxx DD_SITE="datadoghq.eu" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"
` on a ubuntu machine.

**Additional environment details (Operating System, Cloud provider, etc):**
Machine:	Ubuntu 16.04.6 LTS xenial
Cloud provider: Amazon AWS EC2

**Comment by mx-psi** [comment]
Hi @xeroxoid, I can't reproduce your issue. Would you mind re-running the script to see if it was a fluke? If after re-running it still doesn't work, can you send the output of the following commands?

- `apt-get update`
-  `apt-cache madison datadog-agent`
- `uname -a`

Thank you!

**Comment by xeroxoid** [comment]
Thanks for the response @mx-psi.

It did work on another server so I guess it might be some apt/package cache issue.

On the original one it still produces the same error. The output requested is as follows:

**sudo apt-get update:**
```
Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Hit:4 http://ppa.launchpad.net/certbot/certbot/ubuntu xenial InRelease
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Hit:6 https://apt.datadoghq.com stable InRelease
Get:7 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main Sources [348 kB]
Get:8 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1,170 kB]
Get:9 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [800 kB]
Fetched 2,643 kB in 1s (2,271 kB/s)
Reading package lists... Done
```

**apt-cache madison datadog-agent:**
```
N: Unable to locate package datadog-agent
```

**uname -a:**
```
Linux foo 4.4.0-169-generic #198-Ubuntu SMP Tue Nov 12 10:38:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by KSerrania** [comment]
I think the problem here comes from the apt list cache, which thinks that our repository has an `InRelease` file:

```
Hit:6 https://apt.datadoghq.com stable InRelease
```

while the repository does not: https://apt.datadoghq.com/dists/stable/ (you can see that we're using `Release` + `Release.gpg` and not an `InRelease` file).

The most plausible reason to this is that a while ago, we accidentally pushed an `InRelease` file for a short while on the repo, and your host did an `apt-get update` at that moment, adding this file to your list cache. Since apt prefers `InRelease` files to `Release` + `Release.gpg`, the next `apt-get update` would take the cached `InRelease` file and ignore the remote repository's `Release` file (which is the one we actually update).

The easiest way to confirm this is to look at `/var/lib/apt/lists` on your host. If there's a file named `apt.datadoghq.com_dists_stable_InRelease` there, that would confirm that this is the case. Then, the easiest way to fix the list cache would be to remove all files starting with `apt.datadoghq.com` in `/var/lib/apt/lists`, then doing `sudo apt-get update` to rebuild the apt cache for the repository.

If everything goes well, the `sudo apt-get update` output should contain something along the lines of:

```
Ign:4 https://apt.datadoghq.com stable InRelease
Hit:5 https://apt.datadoghq.com stable Release
```

**Comment by xeroxoid** [comment]
Perfect, that worked! Thanks @KSerrania !
