### ISSUE TITLE
go mod vendor fails

### ISSUE THREAD

**Issue by fzipi** [DataDog/datadog-agent#6262]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**

```
❯ go version
go version go1.14.6 linux/amd64
❯ go mod vendor
go: github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
```

**Describe what you expected:**

All resources vendored properly.

**Steps to reproduce the issue:**

Execute `go mod vendor`.

**Additional environment details (Operating System, Cloud provider, etc):**

Fedora Linux 32.

**Comment by mx-psi** [comment]
Hi @fzipi! Thanks for bringing this up. Fedora sets `GOPROXY="direct"`, which makes the vendoring fail. You can use `go env -w GOPROXY="https://goproxy.io,direct"` to fix this. We do not officially support Fedora, so that's why it went under our radar.

As a sidenote, to install dependencies, we recommend running `inv deps` after setting up your development environment as documented [here](https://github.com/DataDog/datadog-agent/blob/master/docs/dev/agent_dev_env.md). This will handle the vendoring as well as other dependencies.

**Comment by fzipi** [comment]
Thanks @mx-psi ! That worked well.

I got that part, but this is a shortcut. My main objective is to use it for building in FreeBSD (we had a proper 7.16 package, but updating the go modules requires to have the `vendor/modules.txt` file to use the ports helper tools). So I ended doing that in my laptop, which has Fedora. :)
