### ISSUE TITLE
Unable to build netop from /pkg/network/netop.go

### ISSUE THREAD

**Issue by chiragtayal** [DataDog/datadog-agent#7393]
**Describe what happened:**

I am trying a test to get  network communication stats using datadog-agent using netop.go file but it is cautiously complaining 

```
# github.com/DataDog/datadog-agent/pkg/ebpf/compiler
In file included from compiler.cpp:1:0:
compiler.h:5:38: fatal error: clang/Driver/Compilation.h: No such file or directory
compilation terminated.

clang --version
Ubuntu clang version 11.1.0-++20210204122740+1fdec59bffc1-1~exp1~20210203233413.161
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

cmake --version
cmake version 3.17.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

When I am trying to run without the tag I get following error
```
BPF-based system probe not implemented on non-linux systems
```

I am running it on ubuntu 4.15.0-1080-gcp kernel

**Describe what you expected:**
should be able to execute and see traffic summary

**Steps to reproduce the issue:**
trying to run it using `go run -tags linux_bpf netop.go`

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by brycekahle** [comment]
Hi @chiragtayal! Apologies for the delay in responding. This error is caused because it cannot find our custom build of `clang` with only the eBPF backend. This is currently built in our [CI](https://github.com/DataDog/datadog-agent/blob/a33248c2bc125920a9577af1e16f12298875a4ad/.gitlab/deps_build.yml#L47-L99).

If you follow those same instructions and extract the tarball to `/opt/datadog-agent/embedded`, you should be able to resolve this compilation error.
