### ISSUE TITLE
Windows installer for agent not able to change region

### ISSUE THREAD

**Issue by tobyhalldev** [DataDog/datadog-agent#7492]
**Describe what happened:**

I was seeing `invalid API key` in the `.yaml` settings even though I could validate it with `curl` okay. I suspected that I may have left the region as datadoghq.com in and not used datadoghq.eu when I installed it. The bugs I am reporting are that:

* The **Change** button in the Windows installer does nothing
* When you do a **Repair** I suspect it does not change the original setting of .com over .eu because I still got the error. Yet when I uninstalled and reinstalled with the .eu domain it is now working.

Also, I couldn't find where the region domain is set/changed after installer is run?

**Additional environment details (Operating System, Cloud provider, etc):**

Windows 10.

**Comment by tobyhalldev** [comment]
I still came across this issue a few days ago when i tried it on a Ubuntu box.
 Is this going to be resolved. The same things but in Ubuntu. Could this be fixed please. @sgnn7

**Comment by sgnn7** [comment]
Hey @tobyhalldev, I added the label so that the appropriate team can answer your original question. 

I sadly don't know enough about exact installer settings you are mentioning but I believe that using `SITE` (Windows) / `DD_SITE` (Linux) env vars should get your installation to use those [servers](https://docs.datadoghq.com/getting_started/site/). If you need to change the setting post-install, you can directly edit [Agent's configuration files](https://docs.datadoghq.com/agent/guide/agent-configuration-files/?tab=agentv6v7) in either `/etc/datadog-agent/datadog.yaml` (Linux) or `%ProgramData%\Datadog\datadog.yaml` (Windows) and change the [`site:` setting](https://github.com/DataDog/datadog-agent/blob/main/pkg/config/config_template.yaml#L13-L21) to the appropriate value.

**Comment by tobyhalldev** [comment]
Oh thanks for looking into this @sgnn7  I will keep an eye on it.

**Comment by clarkb7** [comment]
If the configuration file `%ProgramData%\Datadog\datadog.yaml` already exists then the installer will not modify it. We don't have plans to change this behavior at the moment. You can follow @sgnn7's instructions to edit the configuration file.
