### ISSUE TITLE
Proxy deprecation warning about configuration option no_proxy_nonexact_match

### ISSUE THREAD

**Issue by deisenzimmer** [DataDog/datadog-agent#8274]
In transport.go, there appears to be phasing in for a new proxy module function.

I cannot get the new function to behave the same as the old.

There must be something simple I am missing.  Can anyone help?

See: https://github.com/DataDog/datadog-agent/blob/be3e69b8c8577b98c714b95eb689118f415699a0/pkg/util/http/transport.go#L150-L163

**Describe what happened:**

My logs are showing these message pairs after debug is enabled:

```
2021-05-28 10:13:59 CDT | CORE | DEBUG | (pkg/util/http/transport.go:120 in 1) | Using proxy http://webproxy.internal.qa.mysite.com:3128 for URL 'https://api.datadoghq.com'
2021-05-28 10:13:59 CDT | CORE | WARN | (pkg/util/http/transport.go:136 in func2) | Deprecation warning: the HTTP request to https://api.datadoghq.com uses proxy http://webproxy.internal.qa.mysite.com:3128/ but will ignore the proxy when the Agent configuration option no_proxy_nonexact_match defaults to true in a future agent version. Please adapt the Agent’s proxy configuration accordingly
```

**Describe what you expected:**

The new function returns the same proxy URL as the old function for my configuration.

**Steps to reproduce the issue:**

In datadog.yaml:
```
proxy:
  https: http://webproxy.internal.qa.mysite.com:3128/
  http: http://webproxy.internal.qa.mysite.com:3128/
  no_proxy:
    - 127.0.0.1
```

**Additional environment details (Operating System, Cloud provider, etc):**

Datadog Agent v7.27.0 on Amazon Linux 2

**Comment by olivielpeau** [comment]
Hi @deisenzimmer, thanks for reporting this! There is currently a flaw in the logic that logs these warnings that makes them appear in cases where they shouldn't be logged (false positives), sorry for the confusion. This will be fixed in the upcoming Agent v7.29.0 (related PR: https://github.com/DataDog/datadog-agent/pull/7930).

In your specific case (for the proxy configuration you shared), the new proxy logic has the same behavior as the old one so you can safely set `no_proxy_nonexact_match` to `true` in your agent configuration to use the new proxy logic (and stop seeing these warnings).

Since the fix has been merged, I'll go ahead and close this issue, but let me know if you have further questions, thanks!
