### ISSUE TITLE
Agent tries to connect to 7-29-1-app.datadoghq.com, which does not resolve over privatelink.

### ISSUE THREAD

**Issue by cl-ewhite** [DataDog/datadog-agent#8692]
Using AWS VPC Endpoints:
com.amazonaws.vpce.us-east-1.vpce-svc-0d560852f6f1e27ac
com.amazonaws.vpce.us-east-1.vpce-svc-025a56b9187ac1f63
com.amazonaws.vpce.us-east-1.vpce-svc-0ed1f789ac6b0bde1

The agent tries to go to 7-29-1-app.agent.datadoghq.com

This DNS does not resolve over private link.
However, agent.datadoghq.com does resolve.  Showing my VPC Endpoint is correctly configured.

I cannot find the value 7-29-1 in any config file, so I don’t know where it is coming from.

[root@prod.irisqa1.db_mgmt datadog-agent]# dig agent.datadoghq.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.amzn2.0.4 <<>> agent.datadoghq.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11040
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;agent.datadoghq.com.           IN      A

;; ANSWER SECTION:
agent.datadoghq.com.    60      IN      A       172.22.15.107
agent.datadoghq.com.    60      IN      A       172.22.15.252

;; Query time: 1 msec
;; SERVER: 172.22.15.2#53(172.22.15.2)
;; WHEN: Fri Jul 23 12:42:46 EDT 2021
;; MSG SIZE  rcvd: 80

[root@prod.irisqa1.db_mgmt datadog-agent]# dig^C
[root@prod.irisqa1.db_mgmt datadog-agent]# dig 7-29-1-app.agent.datadoghq.com

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.amzn2.0.4 <<>> 7-29-1-app.agent.datadoghq.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 7924
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;7-29-1-app.agent.datadoghq.com.        IN      A

;; Query time: 0 msec
;; SERVER: 172.22.15.2#53(172.22.15.2)
;; WHEN: Fri Jul 23 12:42:55 EDT 2021
;; MSG SIZE  rcvd: 59

[root@prod.irisqa1.db_mgmt datadog-agent]#

**Comment by olivielpeau** [comment]
@cl-ewhite This is now fixed with a new VPC endpoint for metrics: `com.amazonaws.vpce.us-east-1.vpce-svc-09a8006e245d1e7b8`, see our [updated docs](https://docs.datadoghq.com/agent/guide/private-link/?tab=metrics#create-your-vpc-endpoint).

Please remove the previous metrics PrivateLink endpoint (`com.amazonaws.vpce.us-east-1.vpce-svc-0d560852f6f1e27ac`) from your VPC before setting up this new, updated endpoint. The new endpoint does not require the `dd_url`/`DD_DD_URL` config option to be set to any specific value, it should be left unset in Agent config.

I'll go ahead and close this issue, but feel free to re-open and comment here if you're still running into issues with AWS PrivateLink, thanks!
