### ISSUE TITLE
how to create mock agent?

### ISSUE THREAD

**Issue by DanielAmmar** [DataDog/datadog-agent#9885]
We have additional dev environments where we don't want to monitor.
These environment are "mirror" to our production environment, but it order to save costs we would like to remove the agents there.
Unfortunately, our code tries to connect to the agent and send some metrics/apm/ etc.
Since we don't want to just remove the agent and get some waste error messages, our solution is to set the DD_API_KEY to some invalid string:
DD_API_KEY=INVALID_KEY_TO_NOT_SEND_DATA

I would like to know if there is a cleaner way to do so?
Additionally, would it be sufficient to set 'DD_APM_ENABLED', 'DD_PROCESS_AGENT_ENABLED',  'DD_LOGS_ENABLED' & 'DD_PROFILING_ENABLED' to False?

**Comment by sgnn7** [comment]
@DanielAmmar The extra env vars would reduce the footprint but the agent itself would still try to send data. Ideally the agents would just not run in that environment but if you're trying to avoid that I think the easiest option would be to maybe set the `DD_SITE=localhost` (or something similar) which should send all data to the non-existent endpoint. Since this isn't an issue in the traditional sense of the word I'll close it but feel free to let us know if the suggestion doesn't work.
